### ISSUE TITLE
Unable to run node commands in script

### ISSUE THREAD

**Issue by michael-e** [klaascuvelier/SublimeCommandOnSave#1]
I am trying to execute s.th. as simple as

```
uglifycss app.css > app.min.css
```

in a bash script on save. But the output file `app.min.css` is always empty.

The same command works fine in Sublime Text 2 (using the ST2 plugin), on the same computer.

All "native" bash commands work as expected.

I can't figure out what might be the problem. Do you have any ideas?

**Comment by klaascuvelier** [comment]
I can't give a direct explanation for this.
Maybe it's worth trying some "debugging" by using commands like `echo "ok" > app.min.css` and `cat app.css > app.min.css` to see what exactly goes wrong.

To be honest, I don't use this plugin anymore myself, but I'm happy to help you figure out what goes wrong

**Comment by michael-e** [comment]
Both commands work fine, like all the other "native" shell/bash commands. Only the node packages (e.g. `uglifycss` or `uglifyjs`) don't work when the script is executed by the ST3 plugin.

I also tried to include absolute paths, to no avail. I am running out of ideas, so I may have to postpone the switch to Sublime Text 3 (or find a different solution to watch the folders).

**Comment by klaascuvelier** [comment]
did you try the absolute paths for the files, or for the node package?
Maybe `/usr/local/bin/uglifycss app.css > app.min.css` works?

**Comment by michael-e** [comment]
I tried all combinations of absolute/relative paths. 

For debugging, would it be possible to catch any output of the shell script and write it to a log file?

**Comment by michael-e** [comment]
I now added `exec &> logfile.txt`  to the top of my script in order to catch the output.

When I run `uglifycss app.css > app.min.css`, the output is:

> /some/path/deploy.sh: line 9: uglifycss: command not found

When I run `/usr/local/bin/uglifycss app.css > app.min.css`, the output is:

> env: node: No such file or directory

Any ideas?

**Comment by michael-e** [comment]
This look like a `PATH` issue, doesn't it? Is either Sublime Text or the plugin running as a different user when using Sublime Text 3 (compared to Sublime Text 2)?

**Comment by michael-e** [comment]
I solved it!

    /usr/local/bin/node /usr/local/bin/uglifycss app.css > app.min.css

It's not elegant, but it works.

**Comment by klaascuvelier** [comment]
Yeah I suspected path issues. Good that you solved it. Maybe you can contact the Sublime creator to see if this is a new issue or if this is by design. It might be possible to push your existing path variable into the ST3 env

**Comment by michael-e** [comment]
Thanks a lot!

**Comment by michael-e** [comment]
Unfortunately, there is no place to report bugs (apart from the ST forum). Fingers crossed!

<https://forum.sublimetext.com/t/bug-report-path-issues-in-environment/25093>

**Comment by klaascuvelier** [comment]
Keep me posted on the outcome, maybe I'd be able to fix it somehow :)

**Comment by michael-e** [comment]
There is zero outcome in the Sublime Forum. Feel free to close this this issue if you like (since it seems to be a problem of the "Sublime Text 3 eternal beta").

**Comment by klaascuvelier** [comment]
That's too bad @michael-e. I'll close it now, feel free to reopen or recreate a ticket if anything would come up.
