### ISSUE TITLE
Settings file per Project

### ISSUE THREAD

**Issue by ggedde** [klaascuvelier/SublimeCommandOnSave#2]
Hi there,
I would really like to use this Plugin, but curious if you can add a feature to allow the settings to be in a file on the root of the project.  
Ex.
   save_commands.json  (Preferred)
   .commandonsave
   command_on_save.json
   Etc.

The reason is I would really like to allow the settings for this to be transmitted with GIT.  This way another developer that pulls down my code it will start working for him right away as long as he has the Plugin installed.

Bonus points if you decide to also have this available on Atom.
Thanks

**Comment by klaascuvelier** [comment]
That's a great suggestion @ggedde!
I'll see how quickly/easily I can implement this.
