### ISSUE TITLE
Two errors on sublime text4

### ISSUE THREAD

**Issue by crimestop** [klaascuvelier/SublimeCommandOnSave#7]
On sublime text4 with python3.3 as default compiler, there're two errors:

1. NameError: global name 're' is not defined
solution:
insert
```
import re
```
2. FileNotFoundError: [Errno 2] No such file or directory: 'rsync ...'
solution:
insert
```
import shlex
```
then replace
```
 process = subprocess.Popen(command,
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```
by
```
 process = subprocess.Popen(shlex.split(command),
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```

**Comment by klaascuvelier** [comment]
Hi @crimestop thanks for reporting this issue. It's been a while since I used this plugin myself so I did not notice the issue yet. But I will try and have a look at this asap!

**Comment by crimestop** [comment]
Seems this is a bug only for the Release version. Your latest code is correct.

**Comment by klaascuvelier** [comment]
Ah good to hear. I'll close this for now. Enjoy using the plugin, let me know if there's anything I can improve :)
